import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { UserProfile } from "@/components/daydot/layout/Header/UserProfile";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex max-h-screen flex-col items-center bg-white text-gray-900">
        <Providers>
          <div className="flex h-screen w-full max-w-[470px] flex-col bg-gray-50">
            {/* Header */}
            <header className="flex h-12 items-center justify-between px-4">
              <div className="flex items-end gap-1">
                <span className="text-2xl font-extrabold tracking-tight">
                  DayDot
                </span>
                <div className="bg-primary mb-1.5 h-2 w-2 rounded-full" />
              </div>
              <UserProfile />
            </header>

            {/* Main */}
            <main className="relative flex-1 overflow-y-auto p-4">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
