import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Separator } from "@/components/ui/separator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const FOOTER_MENU = [
    {
      title: "Home",
      icon: (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="var(--color-gray-600)"
          className="size-6"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"
          />
        </svg>
      ),
      url: "",
    },
    {
      title: "History",
      icon: (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="var(--color-gray-600)"
          className="size-6"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5"
          />
        </svg>
      ),
      url: "",
    },
    {
      title: "Feedback",
      icon: (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="var(--color-gray-600)"
          className="size-6"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10"
          />
        </svg>
      ),
      url: "",
    },
  ];

  return (
    <html lang="en">
      <body className="flex max-h-screen flex-col items-center bg-white text-gray-900">
        <div className="flex h-screen w-full max-w-[470px] flex-col bg-gray-50">
          {/* Header */}
          <header className="flex h-12 items-center justify-between px-4">
            <div className="flex items-end gap-1">
              <span className="text-2xl font-extrabold tracking-tight">
                DayDot
              </span>
              <div className="bg-primary mb-1.5 h-2 w-2 rounded-full" />
            </div>

            <Popover>
              <PopoverTrigger asChild>
                <Button
                  size="custom"
                  variant="outline"
                  className="h-7 border border-gray-400 p-2 text-gray-400"
                >
                  로그인
                </Button>
              </PopoverTrigger>
              <PopoverContent
                align="end"
                className="flex w-fit flex-col items-center px-4 py-2"
              >
                <div className="flex flex-col gap-1">
                  <h1 className="text-[16px] font-bold">DayDot 로그인</h1>
                  <p className="text-[12px] text-gray-500">
                    매일의 점이 모여, 당신을 빛나게 할 거예요 ✨
                  </p>
                </div>
                <Separator className="mt-2 mb-2" />
                <button className="flex h-[41px] w-full cursor-pointer items-center justify-start rounded-full border !border-[#747775] !bg-white !text-[#1F1F1F]">
                  <div>
                    <Image
                      alt=""
                      src="icons/google.svg"
                      width={40}
                      height={40}
                    />
                  </div>
                  <span>Google 계정으로 로그인</span>
                </button>
              </PopoverContent>
            </Popover>
          </header>

          {/* Main */}
          <main className="relative flex-1 overflow-y-auto p-4">
            {children}
          </main>

          {/* Footer (Navigation Bar) */}
          {/* <footer className="flex h-14 items-center justify-around border-t bg-gray-50">
            {FOOTER_MENU.map((menu) => (
              <button key={menu.title} className="flex flex-col items-center">
                {menu.icon}
                <span className="text-[12px] text-gray-600">{menu.title}</span>
              </button>
            ))}
          </footer> */}
        </div>
      </body>
    </html>
  );
}
